/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf --transform 
Files: scene.gltf [121.48KB] > scene-transformed.glb [509.32KB] (-319%)
Author: MANUGR (https://sketchfab.com/MANUGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sunflower-eed0588360284db1bcd4af720c258c10
Title: Sunflower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sunflower/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_OJITAS_0.geometry} material={materials.OJITAS} position={[155.143, 907.101, 9.036]} rotation={[-1.216, Math.PI / 2, 0]} scale={44.285} />
      <mesh geometry={nodes.Cube_GIRASOLITO_0.geometry} material={materials.GIRASOLITO} position={[156.941, 901.146, 5.974]} rotation={[-Math.PI / 2, 0, 0]} scale={[35.999, 124.44, 124.44]} />
      <mesh geometry={nodes.Plane001_HOJA_1_0.geometry} material={materials.HOJA_1} position={[144.302, 1016.036, 7.846]} rotation={[-2.594, Math.PI / 2, 0]} scale={[12.542, 13.822, 12.542]} />
      <mesh geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} position={[156.941, 901.146, 5.974]} rotation={[-Math.PI / 2, 0, 0]} scale={[35.999, 124.44, 124.44]} />
      <instancedMesh args={[nodes.Plane036_HOJA_1_0.geometry, materials.HOJA_1, 10]} instanceMatrix={nodes.Plane036_HOJA_1_0.instanceMatrix} />
      <instancedMesh args={[nodes.Plane002_HOJA_1_0.geometry, materials.HOJA_1, 18]} instanceMatrix={nodes.Plane002_HOJA_1_0.instanceMatrix} />
      <instancedMesh args={[nodes.Plane003_HOJA_1_0.geometry, materials.HOJA_1, 13]} instanceMatrix={nodes.Plane003_HOJA_1_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/sunflower/scene-transformed.glb')
